on:
  push:
    branches:
      - 'main'
    paths:
      - '*.yml'
      - 'modules/*.yml'
  pull_request:
  workflow_dispatch: # can be manually dispatched under GitHub's "Actions" tab
name: Build Flatpak
jobs:
  flatpak:
    name: Flatpak Builder
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-5.15-23.08
      options: --privileged
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
#    - name: Cache
#      id: cache
#      uses: actions/cache@v3
#      if: always()
#      with:
#        path: .flatpak-builder
#        key: flatpak-build-${{ github.sha }}
#        restore-keys: flatpak-build
        
    - name: Build
      uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: qtwebkit.flatpak
        manifest-path: io.qt.qtwebkit.BaseApp.yml
#        cache: false
